version: '3.4'

services:
  ping-server-service:
    container_name: ping-server
    image: ping-server #uses local build
    #image: 10.11.12.54:5000/ping-server:latest
    restart: unless-stopped
